import React from 'react';
import { Cinzel, Manrope } from "next/font/google";

const cinzel = Cinzel({ subsets: ["latin"], weight: ["400", "700"] });
const manrope = Manrope({ subsets: ["latin"], weight: ["300", "500", "700"] });

export const metadata = {
  title: 'Terms & Conditions | LHBS',
  description: 'Terms & Conditions for Live Healthy and Be Safe',
};

const TermsAndConditions = () => {
  return (
    <div className={`max-w-4xl mx-auto px-6 pt-32 pb-20 min-h-screen text-text ${manrope.className}`}>
      <h1 className={`text-4xl md:text-5xl font-bold mb-10 text-center ${cinzel.className}`}>Terms & Conditions</h1>
      
      <div className="space-y-6 text-gray-700 leading-relaxed text-sm md:text-base">
        <p>
          <strong>A.</strong> This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </p>

        <p>
          <strong>B.</strong> This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <a href="https://masterpramod.com/" className="text-primary hover:underline">https://masterpramod.com/</a> (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”).
        </p>

        <p>
          <strong>C.</strong> The Platform is owned by Live Healthy and Be Safe, a company incorporated under the Companies Act, 1956 with its registered office at 267, Goyal nagar, Near Bangali square, Indore MP 452018 (hereinafter referred to as “Platform Owner”, “we”, “us”, “our”).
        </p>

        <p>
          <strong>D.</strong> Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
        </p>

        <p>
          <strong>E.</strong> For the purpose of these Terms of Use, wherever the context so requires “you”, “your” or “user” shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
        </p>

        <p className="font-bold">
          F. ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
        </p>

        <p>
          <strong>G.</strong> The use of Platform and/or availing of our Services is subject to the following Terms of Use:
        </p>

        <ul className="list-none space-y-4 pl-4 md:pl-8">
          <li>
            <strong>I.</strong> To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
          </li>
          <li>
            <strong>II.</strong> Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
          </li>
          <li>
            <strong>III.</strong> Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.
          </li>
          <li>
            <strong>IV.</strong> The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.
          </li>
          <li>
            <strong>V.</strong> You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.
          </li>
          <li>
            <strong>VI.</strong> You agree to pay us the charges associated with availing the Services.
          </li>
          <li>
            <strong>VII.</strong> You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.
          </li>
          <li>
            <strong>VIII.</strong> You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.
          </li>
          <li>
            <strong>IX.</strong> You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
          </li>
          <li>
            <strong>X.</strong> You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
          </li>
          <li>
            <strong>XI.</strong> In no event will the Platform Owner be liable for any indirect, consequential, incidental, special or punitive damages, including without limitation damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data or loss of other economic interests, whether in contract, negligence, tort or otherwise, arising from the use of or inability to use the Services, however caused and whether arising in contract, tort, negligence, warranty or otherwise, exceed the amount paid by You for using the Services giving rise to the cause of action or Rupees One Hundred (Rs. 100) whichever is less.
          </li>
          <li>
            <strong>XII.</strong> Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
          </li>
          <li>
            <strong>XIII.</strong> These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
          </li>
          <li>
            <strong>XIV.</strong> All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in 267, Goyal nagar, Near Bangali square, Indore MP 452018.
          </li>
          <li>
            <strong>XV.</strong> All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
          </li>
        </ul>

        <div className="mt-12 pt-8 border-t border-gray-100 space-y-8">
          <div>
            <h2 className={`text-xl font-bold mb-3 text-black ${cinzel.className}`}>Information provided or collected from access or use of the Site</h2>
            <p>
              When you access or use our Site, we collect information about how you have used our Site and our services. When you access the Site, certain information is stored in our servers automatically. The information captured automatically includes, but is not limited to, the following: data about the pages you access within the Site, user’s choices and behavior, your internet protocol (“IP”) address, device identity or unique identifier, device type, geo-location information (on obtaining consent), device and connection information, mobile network information, statistics on page views, traffic to and from the sites, referral URL, ad data, and standard web log data and other information. We also collect anonymous information through our use of cookies and web beacons. We may collect and store any information you provide us when you use our services, including when you: (i) add information on a web form; (ii) add, edit or update your Account information; (iii) contact us for support or other offerings; (iv) participate in community discussions, chats, etc.; (v) send any messages to us or correspond with us regarding the Site or our services; (vi) respond to a survey conducted by us; (vii) register for a promotion provided by us; (viii) request certain features (e.g., newsletters, updates, etc.); and/or (ix) submit feedback to us. We also collect the content that you create, upload, or post, on the Site.
            </p>
          </div>

          <div>
            <h2 className={`text-xl font-bold mb-3 text-black ${cinzel.className}`}>Cookies and Related Tracking Technologies</h2>
            <p>
              The Site uses persistent and session cookies and other similar technologies to offer you a personalized experience and to remember your browsing preferences, including your log in details and choice of language. Cookies are stored primarily to ensure that in the event you return to the Site, it shall personalize your browsing, including, enabling you to be logged on the Site automatically. This information may, where permitted by applicable law, also be combined with other information we hold about you. The cookies are uniquely assigned to you and can only be accessed by your web page server in our domain. You can disable our cookies or all cookies through your browser settings. Upon the beginning of each of your visits to the Site, the Site also provides the choice to turn off all cookies which are not strictly necessary for the provision of our services. Please be advised that disabling cookies through either method may impact many of the Site’s features. In addition to cookies, we and/or our third-party advertising partners may use technologies that help us better manage and analyse content.
            </p>
          </div>

          <div>
            <h2 className={`text-xl font-bold mb-3 text-black ${cinzel.className}`}>Buttons, Tools & Content from Other Companies</h2>
            <p>
              The Site may include buttons, tools, or content that link to other companies’ services, such as Facebook, Twitter, Instagram, and LinkedIn. We may collect information about your use of these features. In addition, when you see or interact with these buttons, tools, or content, or view a web page on the Site, some information from your browser may automatically be sent to the other company, in accordance with the terms and conditions of such other company.
            </p>
          </div>

          <div>
            <h2 className={`text-xl font-bold mb-3 text-black ${cinzel.className}`}>Contacting the Company</h2>
            <p>
              We may also collect information about you from other sources, such as through your contact with us, including our customer support and/or social media team, and your interactions with other users. Additionally, for quality and training purposes or for our own protection, we may monitor or record telephone conversations with you or anyone acting on your behalf. By communicating with us, you acknowledge that your communication may be overheard, monitored, or recorded without further notice or warning.
            </p>
          </div>
        </div>

      </div>
    </div>
  );
};

export default TermsAndConditions;